/**
 * 构建浏览器 bundle：把 src/client/*（ESM 风格源码模块）打成
 * lib/client.js（零依赖、无构建安装的单一文件）。
 *
 * 这是本项目唯一允许的"微型 bundler"：只支持本仓库约定的语法——
 *  - `import { a, b } from "./module.js";`
 *  - `export function name(...)`
 *  - `export async function name(...)`
 *  - `export const NAME = ...`
 * 不要往 src/client 引入动态 import、export default 或 import *。
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const srcDir = join(root, "src", "client");
const outFile = join(root, "lib", "client.js");
const ENTRY = "index";

function moduleIdOf(spec) {
  const resolved = resolve(srcDir, spec).replace(/\\/g, "/");
  return relative(srcDir, resolved).replace(/\.js$/, "");
}

const cache = new Map(); // id -> { body, deps }
function loadModule(id) {
  if (cache.has(id)) return cache.get(id);
  const file = join(srcDir, `${id}.js`);
  const source = readFileSync(file, "utf8");
  const deps = [];
  const importPattern = /^(\s*)import\s*\{([^}]+)\}\s*from\s*"([^"]+)";\s*$/gm;
  const body = source.replace(importPattern, (_match, indent, names, spec) => {
    const depId = moduleIdOf(spec);
    deps.push(depId);
    return `${indent}const { ${names.trim()} } = __modules[${JSON.stringify(depId)}];`;
  });
  const module = { body, deps };
  cache.set(id, module);
  for (const dep of deps) loadModule(dep);
  return module;
}

function transformExports(body) {
  const exported = [];
  let text = body;
  text = text.replace(/^(\s*)export\s+async\s+function\s+([A-Za-z0-9_$]+)/gm, (_m, indent, name) => {
    exported.push(name);
    return `${indent}async function ${name}`;
  });
  text = text.replace(/^(\s*)export\s+function\s+([A-Za-z0-9_$]+)/gm, (_m, indent, name) => {
    exported.push(name);
    return `${indent}function ${name}`;
  });
  text = text.replace(/^(\s*)export\s+const\s+([A-Za-z0-9_$]+)\s*=/gm, (_m, indent, name) => {
    exported.push(name);
    return `${indent}const ${name} =`;
  });
  if (exported.length > 0) {
    text += "\n" + exported.map((name) => `__export(${JSON.stringify(name)}, ${name});`).join("\n");
  }
  return text;
}

loadModule(ENTRY);
const ordered = [];
const seen = new Set();
(function visit(id) {
  if (seen.has(id)) return;
  seen.add(id);
  for (const dep of cache.get(id).deps) visit(dep);
  ordered.push(id);
})(ENTRY);

const parts = [];
parts.push(`// AUTO-GENERATED by scripts/build-client.js — do not edit by hand.
// 源码：src/client/*（维护入口），本文件是构建产物，用户安装无需构建。
window.__ModuleLoader__.load({
	id: "dsh-billing-glass",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

		const __modules = {};
		const __define = (id, setup) => {
			const __exports = {};
			const __export = (name, value) => { __exports[name] = value; };
			setup(__exports, __export);
			__modules[id] = __exports;
		};
`);
for (const id of ordered) {
  const body = transformExports(cache.get(id).body);
  parts.push(`		__define(${JSON.stringify(id)}, (__exports, __export) => {\n`);
  parts.push(body);
  parts.push(`\n		});\n`);
}
parts.push(`
		const entry = __modules["index"];
		exports.apply = entry.clientPlugin.apply;
		exports.inject = entry.clientPlugin.inject;
		return module.exports;
	}
});
`);

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, parts.join(""), "utf8");
console.log(`build-client: wrote ${outFile} from ${ordered.length} source modules`);
console.log(`modules: ${ordered.join(", ")}`);
